# Generated by Django 4.2.6 on 2023-10-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('online', models.BooleanField()),
                ('free', models.BooleanField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('courses', models.ManyToManyField(to='roadmap.course')),
                ('educationEstablishments', models.ManyToManyField(to='roadmap.educationestablishment')),
                ('exams', models.ManyToManyField(to='roadmap.exam')),
            ],
        ),
    ]
